export default [
  {
    id: "5a4e9y96adk",
    commonname: "",
    wiki: "",
    latinname: "abelia triflora",
    imageurl: "https://practicalplants.org/wiki/abelia_triflora.jpg",
    shade: "light",
    sun: "full",
    water: "moderate",
    hardinesszone: "6",
    heatzone: "",
  },
  {
    id: "cce5sc40msi",
    commonname: "okra",
    wiki: "https://practicalplants.org/wiki/okra",
    latinname: "abelmoschus esculentus",
    imageurl: "https://practicalplants.org/wiki/abelmoschus_esculentus2.jpg",
    shade: "no",
    sun: "full",
    water: "moderate",
    hardinesszone: "",
    heatzone: "",
  },
  {
    id: "iikhsis8fz8",
    commonname: "aibika",
    wiki: "https://practicalplants.org/wiki/aibika",
    latinname: "abelmoschus manihot",
    imageurl: "https://practicalplants.org/wiki/abelmoschus_manihot.jpg",
    shade: "no",
    sun: "full",
    water: "moderate",
    hardinesszone: "9",
    heatzone: "",
  },
]
