export default [
  {
    id: "5a4e9y96adk",
    commonName: "Indian Abelia",
    wiki: "",
    latinName: "abelia triflora",
    imageUrl: "https://pfaf.org/Admin/PlantImages/AbeliaTriflora2.jpg",
    shade: "light",
    sun: "full",
    water: "moderate",
    hardinesszone: "6",
    heatzone: "",
  },
  {
    id: "cce5sc40msi",
    commonName: "okra",
    wiki: "https://practicalplants.org/wiki/okra",
    latinName: "abelmoschus esculentus",
    imageUrl: "https://practicalplants.org/wiki/abelmoschus_esculentus2.jpg",
    shade: "no",
    sun: "full",
    water: "moderate",
    hardinesszone: "",
    heatzone: "",
  },
  {
    id: "iikhsis8fz8",
    commonName: "aibika",
    wiki: "https://practicalplants.org/wiki/aibika",
    latinName: "abelmoschus manihot",
    imageUrl: "https://practicalplants.org/wiki/abelmoschus_manihot.jpg",
    shade: "no",
    sun: "full",
    water: "moderate",
    hardinesszone: "9",
    heatzone: "",
  },
]
